### PR TITLE
Update cwlearnimportingplugins

### PR DESCRIPTION
**Pull request by Vexxy**
Wrong file extension.

### CODE REVIEW

**Comment by Zigalishous** [comment]
I didn't know you knew about this repository.

**Comment by Vexxy** [comment]
I just saw it from nowhere, lol.

**Comment by Zigalishous** [comment]
Not to many know about this project, only the people I have linked to it who needed help with basic customization of clockwork, Conna most likely doesn't know about this due to the fact of his absence, however I wrote him and I'm waiting for a reply on whether or not this repository is allowed to stay up. I don't know if this is a fine project or not, but I noticed there wasn't ANY skeleton git, and I thought this could help put down the support tickets a little bit. I'm suprised something like this wasn't created yet, but It's understandable.

**Comment by Vexxy** [comment]
It's not violating any terms of use. Since you wrote it all by hand, it's sufficiently original enough to classify as something seperate from the Clockwork code.

You shouldn't have any problem with Kuro.

**Pull request merged**
